MagicVilla_Web/Controllers/AuthController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MagicVilla_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            var login = new LoginRequestDTO();
            return View(login);
        }

        [HttpPost]
        [ActionName("Login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginPOST(LoginRequestDTO login)
        {
            APIResponse response = await _authService.LoginAsync<APIResponse>(login);
            if (response is not null && response.IsSuccess)
            {
                // If login is successfull.
                LoginResponseDTO loginResponse = JsonConvert
                    .DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result)!)!;
                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(loginResponse.Token);

                // Logging user in so HttpContext will know wheather the user is logged-in. 
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(
                    ClaimTypes.Name
                    , jwt.Claims.FirstOrDefault(user => user.Type == "unique_name").Value));
                identity.AddClaim(new Claim(
                    ClaimTypes.Role
                    , jwt.Claims.FirstOrDefault(user => user.Type == "role").Value));
                var claimsPrincipal = new ClaimsPrincipal(identity);
                await HttpContext
                    .SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
                
                HttpContext.Session.SetString(SD.SessionToken, loginResponse.Token);
                TempData["success"] = "Login successfully";
                return RedirectToAction(nameof(Index), "Home");
            }

            ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
            TempData["error"] = "Login failed";
            return View(nameof(Login), login);
        }

        [HttpGet]
        public IActionResult Register()
        {
            var register = new RegistrationRequestDTO();
            return View(register);
        }

        [HttpPost]
        [ActionName("Register")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterPOST(RegistrationRequestDTO registration)
        {
            if (!string.Equals(registration.Password, registration.PasswordConfirm, StringComparison.CurrentCulture))
                ModelState.AddModelError(nameof(registration.PasswordConfirm), "Passwords must match");

            if (!ModelState.IsValid)
            {
                TempData["error"] = "Registration failed";
                var register = new RegistrationRequestDTO();
                return View(nameof(Register), register);
            }

            APIResponse response =  await _authService.RegisterAsync<APIResponse>(registration);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Registration successfull";
                return RedirectToAction(nameof(Login));
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken, string.Empty);
            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> villaDTOs = new List<VillaDTO>();
            var response = await _villaService
                .GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
                villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)!);

            return View(villaDTOs);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("CreateVilla")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaPOST(VillaCreateDTO villaCreateDTO)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService
                    .CreateAsync<APIResponse>(villaCreateDTO, HttpContext.Session.GetString(SD.SessionToken));
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Villa created successfully";
                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            TempData["error"] = "Error while creating Villa";
            return View("CreateVilla", villaCreateDTO);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla([FromQuery]int villaId)
        {
            var response = await _villaService
                .GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result)!);
                return View(_mapper.Map<VillaUpdateDTO>(model));
            }

            TempData["error"] = "Error! No such Villa";
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("UpdateVilla")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaPOST(VillaUpdateDTO villaUpdateDTO)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService
                    .UpdateAsync<APIResponse>(villaUpdateDTO, HttpContext.Session.GetString(SD.SessionToken));
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Villa updated successfully";
                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            TempData["error"] = "Error while creating Villa";
            return View("UpdateVilla", villaUpdateDTO);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla([FromQuery] int villaId)
        {
            var response = await _villaService
                .GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result)!);
                return View(model);
            }

            TempData["error"] = "Error! No such Villa";
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("DeleteVilla")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaPOST(VillaDTO villaDTO)
        {
            var response = await _villaService
                .DeleteAsync<APIResponse>(villaDTO.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Villa deleted successfully";
                return RedirectToAction(nameof(IndexVilla));
            }

            TempData["error"] = "Error while deleting Villa";
            return View("DeleteVilla", villaDTO);
        }
    }
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Models.ViewModels;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using MagicVilla_Web.Services;
using Microsoft.AspNetCore.Authorization;
using MagicVilla_Utility;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _mapper = mapper;
            _villaService = villaService;
        }
        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO> villaNumberDTOs = new List<VillaNumberDTO>();
            var response = await _villaNumberService
                .GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
                villaNumberDTOs = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result)!);

            return View(villaNumberDTOs);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVillaNumber()
        {
            var response = await _villaService
                .GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            IEnumerable<VillaDTO> villaList = new List<VillaDTO>();
            if (response is not null && response.IsSuccess)
                villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(response.Result.ToString())!;

            var createVillaNumberViewModel = new CreateVillaNumberViewModel()
            {
                VillaNumber = new VillaNumberCreateDTO(),
                VillaList = villaList.Select(villa => new SelectListItem
                {
                    Text = villa.Name,
                    Value = villa.Id.ToString(),
                })
            };

            return View(createVillaNumberViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("CreateVillaNumber")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumberPOST(CreateVillaNumberViewModel createVillaNumberViewModel)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService
                    .CreateAsync<APIResponse>(createVillaNumberViewModel.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Villa Number created successfully";
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                    
                ModelState.AddModelError("VillaNumber.VillaNo", string.Join('\n', response.ErrorMessages));
            }

            await createVillaNumberViewModel.FillVillaList(_villaService, HttpContext);
            TempData["error"] = "Error while creating Villa Number";
            return View(nameof(CreateVillaNumber), createVillaNumberViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVillaNumber([FromQuery]int villaNo)
        {
            var response = await _villaNumberService
                .GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result)!);
                var updateVillaNumberViewModel = new UpdateVillaNumberViewModel()
                {
                    VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model),
                };
                await updateVillaNumberViewModel.FillVillaList(_villaService, HttpContext);
                return View(updateVillaNumberViewModel);
            }

            TempData["error"] = "Error! No such Villa Number";
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("UpdateVillaNumber")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumberPOST([FromQuery] int villaNo
            , UpdateVillaNumberViewModel updateVillaNumberViewModel)
        {
            if (ModelState.IsValid)
            {
                var responseUpdate = await _villaNumberService
                    .UpdateAsync<APIResponse>(villaNo, updateVillaNumberViewModel.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));
                if (responseUpdate is not null && responseUpdate.IsSuccess)
                {
                    TempData["success"] = "Villa Number updated successfully";
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                    
                ModelState.AddModelError("VillaNumber.VillaNo", string.Join('\n', responseUpdate.ErrorMessages));
            }

            await updateVillaNumberViewModel.FillVillaList(_villaService, HttpContext);
            var responseVillaNumber = await _villaNumberService
                .GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));
            if (responseVillaNumber is not null && responseVillaNumber.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(responseVillaNumber.Result)!);
                updateVillaNumberViewModel.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model);
                TempData["error"] = "Error while updating Villa Number";
                return View(nameof(UpdateVillaNumber), updateVillaNumberViewModel);
            }

            // If error occurred while retrieving VillaNumber. 
            ModelState.AddModelError("VillaNumber.VillaNo", string.Join('\n', responseVillaNumber.ErrorMessages));
            TempData["error"] = "Error while updating Villa Number";
            return View(nameof(UpdateVillaNumber), updateVillaNumberViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVillaNumber([FromQuery] int villaNo)
        {
            var response = await _villaNumberService
                .GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result)!);
                return View(model);
            }

            TempData["error"] = "Error! No such Villa Number";
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("DeleteVillaNumber")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumberPOST(VillaNumberDTO villaNumberDTO)
        {
            var response = await _villaNumberService
                .DeleteAsync<APIResponse>(villaNumberDTO.VillaNo, HttpContext.Session.GetString(SD.SessionToken));
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Villa Number deleted successfully";
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            TempData["error"] = "Error while deleting Villa Number";
            return RedirectToAction(nameof(DeleteVillaNumber), new { villaNo = villaNumberDTO.VillaNo});
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"> @* CSS for bootstrap icons *@
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                        </li>
                        @if (!string.IsNullOrEmpty(accessor.HttpContext.Session.GetString(SD.SessionToken)))
                        {
                            // User is logged-in.
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="display: block">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if(TempData["success"] is not null){
    <script type="text/javascript">
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            icon: "success",
            title: "@TempData["success"]"
        });
    </script>
}

@if (TempData["error"] is not null)
{
    <script type="text/javascript">
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            icon: "error",
            title: "@TempData["error"]"
        });
    </script>
}